#CONFIGURA O DIRETORIO DE TRABALHO
setwd("C:/Users/rianm/Documents/Rian/Mestrado_UFF/Artigos/Atropelamento_pedestres/dados")

#IMPORTA A BASE DE DADOS (POR PESSOAS)
pessoas <- read.csv("2017-2019.csv", sep = ";", colClasses = c("data_inversa" = "Date"))

unique(unlist(strsplit(as.character(df5$tipo_acidente), ",")))

#ATROPELAMENTO PESSOAS
pessoas <- subset(pessoas, (tipo_acidente == "Atropelamento de Pedestre" | tipo_acidente == "Atropelamento de Pedestre                                                                                                                                                                               ") & (tipo_envolvido == "Pedestre            " | tipo_envolvido == "Pedestre" ))
rownames(pessoas) <- 1:nrow(pessoas)

#CORRIGE O NUMERO DAS LINHAS
row.names(pessoas) <- 1:nrow(pessoas)

#INSERE A COLUNA ID
pessoas$id <- 1:nrow(pessoas)

#POSICIONA ID NA PRIMEIRA COLUNA
pessoas <- pessoas[, c(29, 1:28)]

# VERIFICACAO DE PESSOAS DUPLICADAS
a <- pessoas[duplicated(pessoas$pesid), ]
b <- pessoas[pessoas$pesid %in% a$pesid,]

remove(a, b)

unique(unlist(strsplit(as.character(pessoas$tipo_envolvido), ",")))
unique(unlist(strsplit(as.character(pessoas$causa_acidente), ",")))
unique(unlist(strsplit(as.character(pessoas$condicao_metereologica), ",")))
unique(unlist(strsplit(as.character(pessoas$fase_dia), ",")))
unique(unlist(strsplit(as.character(pessoas$dia_semana), ",")))
unique(unlist(strsplit(as.character(pessoas$uso_solo), ",")))
unique(unlist(strsplit(as.character(pessoas$feriados), ",")))
unique(unlist(strsplit(as.character(pessoas$tipo_pista), ",")))
unique(unlist(strsplit(as.character(pessoas$tracado_via), ",")))
unique(unlist(strsplit(as.character(pessoas$tipo_acidente), ",")))
unique(unlist(strsplit(as.character(pessoas$tipo_veiculo), ",")))

#CORRECAO EM CLASSIFICACOES DUPLICADAS (BASE PESSOAS)
pessoas$causa_acidente <- gsub("Ingestão de álcool", "Ingestão de Álcool", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Defeito na via", "Defeito na Via", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Defeito na Via                                                                                      ", "Defeito na Via", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Condutor Dormindo                                                                                   ", "Condutor Dormindo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Dormindo", "Condutor Dormindo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Condutor Condutor Dormindo" , "Condutor Dormindo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ultrapassagem Indevida                                                                              ", "Ultrapassagem Indevida", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Velocidade Incompatível                                                                             ", "Velocidade Incompatível", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Velocidade incompatível", "Velocidade Incompatível", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Não guardar distância de segurança                                                                  ", "Não guardar distância de segurança", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Animais na Pista                                                                                    ", "Animais na Pista", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Falta de atenção", "Falta de Atenção à Condução" , pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Falta de Atenção à Condução                                                                         ", "Falta de Atenção à Condução" , pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Defeito Mecânico no Veículo", "Falta de Manutenção no Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Defeito Mecânico no Veículo                                                                         ", "Falta de Manutenção no Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Avarias e/ou desgaste excessivo no pneu", "Falta de Manutenção no Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Defeito mecânico em veículo", "Falta de Manutenção no Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Falta de Manutenção no Veículo                                                             ", "Falta de Manutenção no Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Falta de Manutenção no Veículo            ", "Falta de Manutenção no Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Álcool", "Ingestão de Álcool e/ou Substâncias Psicoativas", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Substâncias Psicoativas", "Ingestão de Álcool e/ou Substâncias Psicoativas", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Álcool                                                                                  ", "Ingestão de Álcool e/ou Substâncias Psicoativas", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Substâncias Psicoativas                                                                 ", "Ingestão de Álcool e/ou Substâncias Psicoativas", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Álcool e/ou Substâncias Psicoativas                                                                                  ", "Ingestão de Álcool e/ou Substâncias Psicoativas", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Pista Escorregadia                                                                                  ", "Pista Escorregadia", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Sinalização da via insuficiente ou inadequada                                                       ", "Sinalização da via insuficiente ou inadequada", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Deficiência ou não Acionamento do Sistema de Iluminação/Sinalização do Veículo                      ", "Deficiência ou não Acionamento do Sistema de Iluminação/Sinalização do Veículo", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Restrição de Visibilidade                                                                           ", "Restrição de Visibilidade" , pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Fenômenos da Natureza                                                                               ", "Fenômenos da Natureza" , pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Agressão Externa                                                                                    ", "Agressão Externa" , pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Mal Súbito                                                                                          ", "Mal Súbito", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Carga excessiva e/ou mal acondicionada                                                              ", "Carga excessiva e/ou mal acondicionada", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Objeto estático sobre o leito carroçável                                                            ", "Objeto estático sobre o leito carroçável", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Falta de Atenção do Pedestre                                                                        ", "Falta de Atenção do Pedestre", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Álcool e/ou Substâncias Psicoativas                                                                 ", "Ingestão de Álcool e/ou Substâncias Psicoativas", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Desobediência às normas de trânsito pelo condutor                                                   ", "Desobediência às normas de trânsito pelo condutor", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Falta de Atenção do Pedestre                                                                        ", "Falta de Atenção do Pedestre", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Desobediência às normas de trânsito pelo pedestre                                                   ", "Desobediência às normas de trânsito pelo pedestre", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ingestão de Álcool e/ou Substâncias Psicoativas e/ou substâncias psicoativas pelo pedestre", "Ingestão de Álcool e/ou Substâncias Psicoativas pelo pedestre", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ultrapassagem indevida", "Ultrapassagem Indevida", pessoas$causa_acidente)
pessoas$causa_acidente <- gsub("Ultrapassagem Indevida                                                                              ", "Ultrapassagem Indevida", pessoas$causa_acidente)


pessoas$condicao_metereologica <-gsub("Céu Claro", "Ceu Claro", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Nevoeiro/neblina", "Nevoeiro/Neblina", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Ignorada", "Ignorado", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Sol                 ", "Sol", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Nevoeiro/Neblina    ", "Nevoeiro/Neblina", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Vento               ", "Vento", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Garoa/Chuvisco      ", "Garoa/Chuvisco", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Nublado             ", "Nublado", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Neve                ", "Neve", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Ceu Claro           ", "Ceu Claro", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Chuva               ", "Chuva", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <-gsub("Ignorado            ", "Ignorado", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <- gsub("Ignorado", NA, pessoas$condicao_metereologica)
pessoas$condicao_metereologica <- gsub("Granizo             ", "Granizo", pessoas$condicao_metereologica)
pessoas$condicao_metereologica <- gsub("Granizo", NA, pessoas$condicao_metereologica)
pessoas$condicao_metereologica <- gsub("Neve", NA, pessoas$condicao_metereologica)
pessoas$condicao_metereologica <- gsub("(null)", NA, pessoas$condicao_metereologica)
pessoas[is.na(pessoas$condicao_metereologica), "condicao_metereologica"] <- "Ignorado"
pessoas$condicao_metereologica <- gsub("Ignorado", NA, pessoas$condicao_metereologica)

pessoas$fase_dia<-gsub("Plena noite", "Plena Noite", pessoas$fase_dia)
pessoas$fase_dia<-gsub("Plena Noite         ", "Plena Noite", pessoas$fase_dia)
pessoas$fase_dia<-gsub("Pleno dia", "Pleno Dia", pessoas$fase_dia)
pessoas$fase_dia<-gsub("Pleno dia           ", "Pleno Dia", pessoas$fase_dia)
pessoas$fase_dia<-gsub("Pleno Dia           ", "Pleno Dia", pessoas$fase_dia)
pessoas$fase_dia<-gsub("Anoitecer           ", "Anoitecer", pessoas$fase_dia)
pessoas$fase_dia<-gsub("Amanhecer           ", "Amanhecer", pessoas$fase_dia)
pessoas$fase_dia<-gsub("(null)", NA, pessoas$fase_dia)

pessoas$dia_semana <- gsub("Quarta ", "Quarta", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Quinta ", "Quinta", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Sábado ", "Sábado", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Sexta  ", "Sexta", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Terça  ", "Terça", pessoas$dia_semana)

pessoas$uso_solo <- gsub("Sim", "Urbano", pessoas$uso_solo)
pessoas$uso_solo <- gsub("Sim       ", "Urbano", pessoas$uso_solo)
pessoas$uso_solo <- gsub("Urbano       ", "Urbano", pessoas$uso_solo)
pessoas$uso_solo <- gsub("Não", "Rural", pessoas$uso_solo)
pessoas$uso_solo <- gsub("Não       ", "Rural", pessoas$uso_solo)
pessoas$uso_solo <- gsub("Rural ", "Rural", pessoas$uso_solo)
pessoas$uso_solo <- gsub("Rural      ", "Rural", pessoas$uso_solo)

pessoas$tipo_pista <- gsub("Simples             ", "Simples", pessoas$tipo_pista)
pessoas$tipo_pista <- gsub("Simples ", "Simples", pessoas$tipo_pista)
pessoas$tipo_pista <- gsub("Dupla               ", "Dupla", pessoas$tipo_pista)
pessoas$tipo_pista <- gsub("Dupla   " , "Dupla", pessoas$tipo_pista)
pessoas$tipo_pista <- gsub("Múltipla            ", "Múltipla", pessoas$tipo_pista)

pessoas$tracado_via <- gsub("Não Informado                 ", "Não Informado" , pessoas$tracado_via)
pessoas$tracado_via <- gsub("Não Informado", NA, pessoas$tracado_via)
pessoas$tracado_via <- gsub("Reta      ", "Reta" , pessoas$tracado_via)
pessoas$tracado_via <- gsub("Reta                          ", "Reta" , pessoas$tracado_via)
pessoas$tracado_via <- gsub("Reta                    ", "Reta" , pessoas$tracado_via)
pessoas$tracado_via <- gsub("Curva     ", "Curva", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Curva                         ", "Curva", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Curva                    ", "Curva", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Rotatória                     ", "Rotatória", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Viaduto                       ", "Viaduto", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Retorno Regulamentado         ", "Retorno Regulamentado", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Interseção de vias            ", "Interseção de vias", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Desvio Temporário             ", "Desvio Temporário", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Ponte                         ", "Ponte", pessoas$tracado_via)
pessoas$tracado_via <- gsub("Túnel                         ", "Túnel", pessoas$tracado_via)

unique(unlist(strsplit(as.character(pessoas$tipo_veiculo), ",")))
pessoas$tipo_veiculo <- gsub("Utilitário          ", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Utilitário         ", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhonete", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhonete         ", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Camioneta           ", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Camioneta", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Automóvel           ", "Automóvel", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhão-Trator", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Semi-Reboque", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhão-Tanque", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhão            ", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhão-trator     ", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhão-trator", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Semireboque", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Chassi-plataforma", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motocicleta            ", "Motocicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motocicleta         ", "Motocicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motocicletas", "Motocicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motoneta", "Motocicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motoneta            ", "Motocicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Ônibus              ", "Ônibus", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Micro-ônibus        ", "Ônibus", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Micro-ônibus", "Ônibus", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Microônibus", "Ônibus", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros              ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Não Informado       ", "Não identificado", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Ciclomotor", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Reboque", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Charrete", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator de rodas", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Carroça", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Bonde / Trem", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator de esteiras", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator misto", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Carro-de-mao", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Triciclo", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Quadriciclo", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Carroça-charrete    ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Reboque             ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trem-bonde          ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Ciclomotor          ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator de rodas     ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator misto        ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Carro de mão        ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Triciclo            ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator de esteira   ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Quadriciclo         ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Carroça-charrete", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Carro de mão", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trem-bonde", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Trator de esteira", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motor-Casa", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros-charrete    ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros             ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros          ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros     ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros        ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros            ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros         ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros-charrete", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros   ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros  ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros    ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("(null)", NA, pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Não identificado", NA, pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Não Informado", NA, pessoas$tipo_veiculo)

pessoas$tipo_veiculo <- gsub("Caminhão         ", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Caminhão   ", "Caminhão", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Outros ", "Outros", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Bicicleta           " , "Bicicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Utilitário         ", "Utilitário", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Motocicleta            ", "Motocicleta", pessoas$tipo_veiculo)
pessoas$tipo_veiculo <- gsub("Side-car", "Outros", pessoas$tipo_veiculo)

pessoas$sexo <- gsub("Masculino           ", "Masculino", pessoas$sexo)
pessoas$sexo <- gsub("Feminino            ", "Feminino", pessoas$sexo)
pessoas$sexo <- gsub("Não Informado       ", "Não Informado", pessoas$sexo)
pessoas$sexo <- gsub("Ignorado            ", "Ignorado", pessoas$sexo)
pessoas$sexo <- gsub("Ignorado", "Inválido", pessoas$sexo)
pessoas$sexo <- gsub("Não Informado", "Inválido", pessoas$sexo)
pessoas$sexo <- gsub("Masculino", "M", pessoas$sexo)
pessoas$sexo <- gsub("Feminino", "F", pessoas$sexo)
pessoas$sexo <- gsub("Inválido", "I", pessoas$sexo)
pessoas$sexo <- gsub("M", "Masculino", pessoas$sexo)
pessoas$sexo <- gsub("F","Feminino", pessoas$sexo)
pessoas$sexo <- gsub("I","Inválido", pessoas$sexo)
pessoas$sexo <- gsub("Inválido", NA, pessoas$sexo)

unique(unlist(strsplit(as.character(pessoas$idade), ",")))
pessoas[is.na(pessoas$idade), "idade"] <- -1
pessoas[pessoas$idade > 100 | pessoas$idade < 10, "idade"] <- NA

pessoas$classificacao_acidente <- gsub("Sem Vítimas        ", "Sem Vítimas", pessoas$classificacao_acidente)
pessoas$classificacao_acidente <- gsub("Com Vítimas Fatais ", "Com Vítimas Fatais", pessoas$classificacao_acidente)
pessoas$classificacao_acidente <- gsub("Ignorado           ", "Ignorado", pessoas$classificacao_acidente)
pessoas$classificacao_acidente <- gsub("(null)", NA, pessoas$classificacao_acidente)

pessoas$dia_semana <- gsub("Segunda", "segunda-feira", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Terça", "terça-feira", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Quarta", "quarta-feira", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Quinta", "quinta-feira", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Sexta", "sexta-feira", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Sábado", "sábado", pessoas$dia_semana)
pessoas$dia_semana <- gsub("Domingo", "domingo", pessoas$dia_semana)

pessoas$estado_fisico <- gsub("Ileso        ", "Ileso", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ileso       ", "Ileso", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ileso               ", "Ileso", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ferido Leve ", "Lesões Leves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ferido Leve", "Lesões Leves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Lesões Leves        ", "Lesões Leves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ferido Grave", "Lesões Graves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Lesões Graves       ", "Lesões Graves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Morto       ", "Morto", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Óbito               ", "Morto", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Óbito", "Morto", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ignorado    ", "Ignorado", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Não Informado       ", "Não Informado", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ileso", "1.Ileso", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Lesões Leves", "2.Lesões Leves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Lesões Graves", "3.Lesões Graves", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Morto", "4.Morto", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("(null)", "excluir", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Não Informado", "Ignorado", pessoas$estado_fisico)
pessoas$estado_fisico <- gsub("Ignorado", "(excluir)", pessoas$estado_fisico)
pessoas[pessoas$estado_fisico == "(excluir)", "estado_fisico"] <- NA

pessoas[pessoas$uf == "(null)", "uf"] <- NA


#TRANSFORMA TIPO DE VEICULO == "" EM NA
sub1 <- subset(pessoas, tipo_veiculo == "")
pessoas[sub1$id, "tipo_veiculo"] <- NA
sub <- pessoas[is.na(pessoas$tipo_veiculo), ]
remove(sub, sub1)
